=== al3xv01d/sandbox/_xml/002 DTD/002 DTD/note.dtd
<?xml version="1.0" encoding="utf-8" ?>
<!ELEMENT note ANY>
<!ELEMENT name ANY>
<!ELEMENT street ANY>
<!ELEMENT city ANY>
<!ELEMENT state ANY>
<!ELEMENT zipcode ANY>
<!ENTITY % customer "name, street, city, state, zipcode">
<!ELEMENT invoice (%customer;, item, price, date)>
<!ELEMENT item ANY>
<!ELEMENT price ANY>
<!ELEMENT date ANY>

=== al3xv01d/sandbox/_xml/002 DTD/002 DTD/009 DTD Entity.xml
<?xml version="1.0" encoding="utf-8" ?>
<!DOCTYPE note SYSTEM "note.dtd">
<note>
  <invoice>
    <name>
      text
    </name>
    <street>
      text
    </street>
    <city>
      text
    </city>
    <state>
      text
    </state>
    <zipcode>
      text
    </zipcode>
    <item>
      text
    </item>
    <price>
      text
    </price>
    <date>
      text
    </date>
  </invoice>
</note>
